[package]
name = "agentos-cli"
edition.workspace = true
version.workspace = true

[[bin]]
name = "agentos"
path = "src/main.rs"

[dependencies]
agentos-core = { path = "../agentos-core" }
agentos-store = { path = "../agentos-store" }
agentos-engine = { path = "../agentos-engine" }
clap.workspace = true
reqwest.workspace = true
rustix = { workspace = true, features = ["system", "fs"] }
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
axum = "0.8.9"
askama = "0.16.1"
base64.workspace = true
getrandom.workspace = true
blake3.workspace = true
tar = "0.4.46"
tokio-util = { version = "0.7.19", features = ["io"] }

[dev-dependencies]
reqwest = { workspace = true, features = ["cookies", "form"] }
tower = { version = "0.5.3", features = ["util"] }
rusqlite.workspace = true
assert_cmd.workspace = true
predicates.workspace = true
serde_json.workspace = true
tempfile.workspace = true
