[package]
name = "agentos-store"
edition.workspace = true
version.workspace = true

[dependencies]
agentos-core = { path = "../agentos-core" }
uuid.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
rustix = { workspace = true, features = ["fs"] }

[dev-dependencies]
tempfile.workspace = true
